name:                syfil
version:             1.1.1
github:              "marvertin/safe-backup"
license:             BSD3
author:              "Martin Veverka"
maintainer:          "martin.veverka@email.cz"
copyright:           "2018 Martin Veverka"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/safe-backup#readme>

dependencies:
- base >= 4.7 && < 5
- cryptohash
- filemanip
- system-filepath
- containers
- directory
- bytestring
- directory-tree
- utf8-string
- filepath
- time
- regex-compat
- regex-posix
- optparse-applicative
- raw-strings-qq
- Unique
- yaml
- text
- timeit
- aeson
- unordered-containers
- either
- transformers
- counter
- raw-strings-qq
- terminal-size
- executable-path


# - derive

library:
  source-dirs: src

executables:
  syfil:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syfil

tests:
  syfil-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - syfil
